---
settings:
  name: SaaS Backup For Salesforce
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: false
  langs: de-de,us-en,ja-jp,zh-cn,zh-tw,ko-kr,fr-fr
sidebar:
  entries:
  - title: NetApp SaaS Backup für Salesforce Dokumente
    url: "/index.html"
  - title: Versionshinweise
    entries:
    - title: Was ist neu
      url: "/reference_new_salesforce.html"
    - title: Bekannte Probleme und Einschränkungen
      url: "/concept_kpls.html"
  - title: Überblick
    url: "/concept_overview.html"
  - title: Managen von SaaS Backup für Salesforce
    entries:
    - title: Backup-Richtlinien
      url: "/reference_backup_policies.html"
    - title: Ein sofortiges Backup durchführen
      url: "/task_performing_immediate_backup.html"
    - title: Aktivieren und Deaktivieren von Metadaten-Backups
      url: "/task_enable_disable_metadata_backups.html"
    - title: Wiederherstellen von Daten
      url: "/task_managing_restores.html"
    - title: Vergleichen und Wiederherstellen von Backup-Unterschieden
      url: "/task_comparing_restoring.html"
    - title: Daten und Metadaten werden entfernt
      url: "/task_purging_data_&_metadata.html"
    - title: Neuauthentifizierung
      url: "/task_reauthenticating.html"
    - title: Abbrechen eines Jobs
      url: "/task_canceling_job.html"
  - title: Daten anzeigen
    entries:
    - title: Anzeigen des Jobverlaufs
      url: "/task_viewing_job_history.html"
    - title: Anzeigen des Aktivitätsprotokolls
      url: "/task_viewing_activity_log.html"
    - title: Das Aktivitätsprotokoll wird heruntergeladen
      url: "/task_downloading_activity_log.html"
    - title: Exportdaten werden heruntergeladen
      url: "/task_downloading_export_data.html"
    - title: Anzeigen von Backup-Datensätzen
      url: "/task_viewing_backup_records.html"
  - title: Feedback mitteilen
    url: "/task_providing_feedback.html"
  - title: Wo Sie Hilfe und weitere Informationen erhalten
    url: "/concept_get_help_find_info.html"
  - title: Rechtliche Hinweise
    url: "/reference_legal_notices.html"
